### ISSUE TITLE
Got an error when `node_modules` mislinked to a file

### ISSUE THREAD

**Issue by yuey11** [pwwang/pipen-report#4]
Hi, Panwen,

After successfully running the pipeline the first time, I tried to update the "FindClusters = {resolution = 0.8}" parameter to rerun the pipeline to get fewer clusters. 
However, I got an error as below:
 
"FileExistsError: [Errno 17] File exists: '/opt/conda/envs/immunopipe/lib/python3.9/site-packages/pipen_report/frontend/node_modules' -> '.pipen/immunopipe/.report-workdir/node_modules'
ERROR conda.cli.main_run:execute(41): `conda run python -m immunopipe --config config.toml` failed. (See above for error)"

Could you please figure that out?

Thanks,
Yue

**Comment by pwwang** [comment]
Should be fixed at [0.4.5](https://github.com/pwwang/pipen-report/releases/tag/0.4.5)
